// Verbatim copy of weight.js from the Claude Design project
// (838e6d66-b09c-4aaf-bc6c-61af84b5f0e8, "Steady Concepts").
// This is the reference implementation of the trend maths. The Swift
// implementation must reproduce it exactly. Do not edit this file.

// Shared demo data + smoothing math for the Steady concepts.
// Deterministic pseudo-random daily weigh-ins, EWMA-smoothed.

const raw = [], trend = [];
(function build() {
  let r = 20260829, w = 74.9;
  const rnd = () => { r = (r * 1103515245 + 12345) % 2147483648; return r / 2147483648; };
  for (let i = 0; i < 400; i++) { w += -0.0065 + (rnd() - 0.5) * 0.95; raw.push(w); }
  const a = 0.18; let e = raw[0];
  raw.forEach((v, i) => { e = i ? a * v + (1 - a) * e : v; trend.push(e); });
})();

const weekly = (arr) => {
  const o = [];
  for (let i = arr.length - 364; i < arr.length; i += 7) o.push(arr.slice(i, i + 7).reduce((s, v) => s + v, 0) / 7);
  return o;
};

export function slice(period) {
  if (period === 'W') return { raw: raw.slice(-7), trend: trend.slice(-7) };
  if (period === 'M') return { raw: raw.slice(-30), trend: trend.slice(-30) };
  // Year: the weekly mean of the smoothed series is almost identical to the
  // weekly mean of the raw one, so the "trend" traced every wiggle. Smooth the
  // weekly points again to keep the line calmer than the dots.
  const wr = weekly(raw), a = 0.3, wt = [];
  let e = wr[0];
  wr.forEach((v, i) => { e = i ? a * v + (1 - a) * e : v; wt.push(e); });
  return { raw: wr, trend: wt };
}

// A 7-point EWMA still wobbles as much as the raw values, which reads wrong:
// over one week the trend should be a calm line and the daily readings should
// scatter above and below it. So the week view fits a least-squares line
// through the week's readings; month/year keep the EWMA.
function fit(y) {
  const n = y.length, mx = (n - 1) / 2;
  const my = y.reduce((s, v) => s + v, 0) / n;
  let num = 0, den = 0;
  y.forEach((v, i) => { num += (i - mx) * (v - my); den += (i - mx) * (i - mx); });
  const m = den ? num / den : 0;
  return y.map((_, i) => my + m * (i - mx));
}

export function chart(period, w, h, padFactor) {
  const s = slice(period);
  if (period === 'W') s.trend = fit(s.raw);
  const all = s.raw.concat(s.trend);
  let mn = Math.min(...all), mx = Math.max(...all);
  const pad = ((mx - mn) || 1) * (padFactor == null ? 0.34 : padFactor);
  mn -= pad; mx += pad;
  const n = s.raw.length;
  const X = (i) => +(n > 1 ? (i / (n - 1)) * w : w / 2).toFixed(1);
  const Y = (v) => +(h - ((v - mn) / (mx - mn)) * h).toFixed(1);
  const dots = s.raw.map((v, i) => ({ cx: X(i), cy: Y(v), key: 'd' + i }));
  const tp = s.trend.map((v, i) => [X(i), Y(v)]);
  return {
    dots,
    // week: bars measure the deviation from the trend line; longer ranges keep
    // the baseline column read.
    bars: dots.map((d, i) => {
      const bw = n > 40 ? 1.2 : n > 10 ? 2.2 : 3.6;
      const ty = Y(s.trend[i]);
      const top = period === 'W' ? Math.min(d.cy, ty) : d.cy;
      const bot = period === 'W' ? Math.max(d.cy, ty) : h;
      return { x: +(d.cx - bw / 2).toFixed(1), y: +top.toFixed(1), w: bw, h: +Math.max(1, bot - top).toFixed(1), key: 'b' + i };
    }),
    ticks: dots.map((d, i) => ({ x: d.cx, y1: +(d.cy - 5).toFixed(1), y2: +(d.cy + 5).toFixed(1), key: 't' + i })),
    rawLine: dots.map(d => d.cx + ',' + d.cy).join(' '),
    trendLine: tp.map(p => p[0] + ',' + p[1]).join(' '),
    trendArea: 'M' + tp.map(p => p[0] + ',' + p[1]).join(' L') + ' L' + w + ',' + h + ' L0,' + h + ' Z',
    dotR: n > 40 ? 1.3 : n > 10 ? 1.8 : 3.4,
    last: tp[tp.length - 1],
    // geometry for overlays such as a target band
    mn, mx, h, yOf: (v) => +Y(v).toFixed(1)
  };
}

// Headline figures for the selected range. Week reports the current week's
// change; month and year report the average change per week (0) and average
// trend weight over the range, with the current week kept as a sub-line.
export function summary(period) {
  const n = trend.length, cur = trend[n - 1];
  if (period === 'W') {
    return { big: cur.toFixed(1), avg: false, perWeek: cur - trend[n - 8], sub: '', scope: 'this week' };
  }
  const span = period === 'M' ? 30 : 364;
  const arr = trend.slice(n - span);
  return {
    big: (arr.reduce((a, b) => a + b, 0) / span).toFixed(1),
    avg: true,
    perWeek: (cur - trend[n - span]) / span * 7,
    sub: 'this week ' + cur.toFixed(1),
    scope: '/ week'
  };
}

const n0 = raw.length;
export const metrics = {
  today: raw[n0 - 1].toFixed(1),
  yesterday: raw[n0 - 2].toFixed(1),
  avg: (raw.slice(-7).reduce((a, b) => a + b, 0) / 7).toFixed(1),
  trendNow: trend[n0 - 1].toFixed(1)
};

export function scale(base, ratio) {
  const up = [base], dn = [];
  for (let i = 0; i < 4; i++) up.push(Math.round(up[up.length - 1] * ratio));
  let b = base;
  for (let i = 0; i < 2; i++) { b = Math.round(b / ratio); dn.unshift(b); }
  return dn.concat(up);
}
